/*
	Sistema: 		Personarium: Sistema de Gestão de Pessoas
    Objetivo:       Inserir carga básica
    Funcionalidade: Gerenciamento de Pessoas e Documentos
    Data: 			01/06/2026
    Demanda: 		PERSONARIUM20260601111341
*/

insert into tb_tipo_pessoa (descricao, sigla) values ('Pessoa Física', 'PF');
insert into tb_tipo_pessoa (descricao, sigla) values ('Pessoa Jurídica', 'PJ');

insert into tb_tipo_documento (nome, sigla) values ('Cadastro de Pessoa Física', 'CPF');
insert into tb_tipo_documento (nome, sigla) values ('Cadastro de Pessoa Física', 'CPF');
insert into tb_tipo_documento (nome, sigla) values ('Registro Geral', 'RG');
insert into tb_tipo_documento (nome, sigla) values ('Carteira Nacional de Habilitação', 'CNH');
insert into tb_tipo_documento (nome, sigla) values ('Título de Eleitor', 'TE');
insert into tb_tipo_documento (nome, sigla) values ('Carteira de Trabalho e Previdência Social', 'CTPS');
insert into tb_tipo_documento (nome, sigla) values ('Passaporte', 'PASSAPORTE');
insert into tb_tipo_documento (nome, sigla) values ('Certidão de Nascimento', 'CN');
insert into tb_tipo_documento (nome, sigla) values ('Certidão de Casamento', 'CC');
insert into tb_tipo_documento (nome, sigla) values ('Documento Nacional de Identificação', 'DNI');
insert into tb_tipo_documento (nome, sigla) values ('Cadastro Nacional da Pessoa Jurídica', 'CNPJ');
insert into tb_tipo_documento (nome, sigla) values ('Inscrição Estadual', 'IE');
insert into tb_tipo_documento (nome, sigla) values ('Inscrição Municipal', 'IM');
insert into tb_tipo_documento (nome, sigla) values ('Contrato Social', 'CS');
insert into tb_tipo_documento (nome, sigla) values ('Microempreendedor Individual', 'MEI');